[package]
name = "body"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2"
plotters = "0.3"
linfa = { git = "https://github.com/rust-ml/linfa" }
linfa-linear = { git = "https://github.com/rust-ml/linfa" }
ndarray = { version = "^0.15.6" }